apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-nginx-service"
spec:
  selector:
    app: {{ .Release.Name | quote }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80