apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
  name: "{{ .Values.app_name }}-ingress"
spec:
  ingressClassName: nginx
  rules:
  - host: "{{ .Values.app_name }}.onyeka.ga"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "{{ .Values.app_name }}-service"
            port:
              number: 80

  # tls:
  # - hosts:
  #   - "{{ .Values.app_name }}.onyeka.ga"
  #   secretName: "{{ .Values.app_name }}.onyeka.ga"
