apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.app_name }}-service"
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    targetPort: 80
    name: web
  clusterIP: None
  selector:
    app: nginx